version: '3.8'

services:
  malawi-graph-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped 